eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.49.2:31108/eureka
server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://127.0.01:5432/hotel_db
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  application:
    name: HOTEL-SERVICE


#  config:
#    import: configserver:http://localhost:8888/