server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  application:
    name: HOTEL-SERVICE


  config:
    import: configserver:http://localhost:8085/ 