eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://13.127.217.126:8761/eureka
server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://hotel-service-db.cto8iauaqiow.ap-south-1.rds.amazonaws.com:5432/hoteldb
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  application:
    name: HOTEL-SERVICE


#  config:
#    import: configserver:http://localhost:8888/